DO $$
DECLARE
	next_id BIGINT;
BEGIN
	SELECT GREATEST(
		CASE WHEN is_called THEN last_value + 1 ELSE last_value END,
		COALESCE((SELECT MAX(id) FROM todoapp.users), 0) + 1
	) INTO next_id FROM todoapp.users_id_seq;

	ALTER TABLE todoapp.users ALTER COLUMN id DROP DEFAULT;
	DROP SEQUENCE todoapp.users_id_seq;
	ALTER TABLE todoapp.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
	PERFORM setval(pg_get_serial_sequence('todoapp.users', 'id'), next_id, false);

	SELECT GREATEST(
		CASE WHEN is_called THEN last_value + 1 ELSE last_value END,
		COALESCE((SELECT MAX(id) FROM todoapp.tasks), 0) + 1
	) INTO next_id FROM todoapp.tasks_id_seq;

	ALTER TABLE todoapp.tasks ALTER COLUMN id DROP DEFAULT;
	DROP SEQUENCE todoapp.tasks_id_seq;
	ALTER TABLE todoapp.tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
	PERFORM setval(pg_get_serial_sequence('todoapp.tasks', 'id'), next_id, false);
END $$;
